### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by ueffel** [malys/keypirinha-rocketchat#1]
There is a problem in your constructor of the plugin.
See the following error log:
```
23:10:08.649 Python: Traceback (most recent call last):
23:10:08.649 Python:   File "keypirinha_private.py", line 356, in reload_module
23:10:08.649 Python:   File "lib\importlib\__init__.py", line 126, in import_module
23:10:08.649 Python:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
23:10:08.649 Python:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
23:10:08.649 Python:   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
23:10:08.649 Python:   File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
23:10:08.649 Python:   File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
23:10:08.649 Python:   File "keypirinha_private.py", line 246, in load_module
23:10:08.649 Python:   File "C:\Users\ueffel\AppData\Roaming\Keypirinha\InstalledPackages\Rocketchat.keypirinha-package\rocketchat.py", line 18
23:10:08.649 Python:     if os.environ['DEBUG'] = 'rocketchat'
23:10:08.649 Python:                            ^
23:10:08.649 Python: SyntaxError: invalid syntax
```

**Comment by malys** [comment]
Hi @ueffel , 
Thx for the information.
I have fixed some bugs and currently, it works fine with our rocketchat server (0.0.1-RC-1).
Bye,

**Comment by ueffel** [comment]
Just fyi: If you want your package to appear in packagecontrol, you need to have a release (not pre release) with a .keypirinha-package file. When you have that, you can submit your package [here](https://ue.spdns.de/packagecontrol/new_package)

**Comment by malys** [comment]
Hi,
 I have tried to register this application:
 
> Form errors:
>     The package source is not available. 

Any ideas?

**Comment by ueffel** [comment]
I tried it just now and it worked. What did you enter?

Should look like this:
![image](https://user-images.githubusercontent.com/2247384/46964928-a6b91d00-d0a9-11e8-8194-ae477c207e45.png)

Well it's in there now :)

**Comment by malys** [comment]
I have entered URL and repository name
